language: ruby
cache: bundler
rvm:
- 2.2.2
script:
- bundle exec cookstyle
- bundle exec foodcritic --contex --epic-fail any .
sudo: false
notifications:
  slack:
    secure: mmq/yRxoOAQDNlLnJZqQwx/2kFGh6JLM2kMaQxNLb1+F17CGQ2gryMsnF/M74ccvr5CNLOjKiuqaMPm4EBfKt/8Nh/xHdDTdWd3MazN0cZGWLu4xYMjwlrctyU3kyVX/jl3HB7WaG0mNus3hQPOMl8LxY9KNq3cH9oBZkco9L24=
